# Generated by Django 4.0.6 on 2022-07-27 13:46

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(blank=True, default='Unknown Episode', max_length=100, unique=True)),
                ('episode_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('episode_file', models.FileField(blank=True, unique=True, upload_to=player.models.Episode_Files, validators=[core.validators.validate_track_extension])),
                ('episode_status', models.BooleanField(default=False)),
                ('episode_release_date', models.DateTimeField()),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, default='Unknown Host', max_length=100, unique=True)),
                ('host_title', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('host_cover', models.ImageField(blank=True, unique=True, upload_to=player.models.Hosts_Profile_Images, validators=[core.validators.validate_image_extension])),
                ('host_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(default='Unknown PlayList', max_length=100)),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PlayList',
                'verbose_name_plural': 'PlayLists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_category_title', models.CharField(blank=True, default='Unknown Genre', max_length=100, unique=True)),
                ('podcast_category_cover', models.ImageField(blank=True, unique=True, upload_to=player.models.Podcast_Categorys_Cover_Images, validators=[core.validators.validate_image_extension])),
                ('podcast_category_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PodcastCategory',
                'verbose_name_plural': 'PodcastCategories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_title', models.CharField(blank=True, default='Unknown Season', max_length=100, unique=True)),
                ('season_cover', models.ImageField(blank=True, unique=True, upload_to=player.models.Seasons_Cover_Images, validators=[core.validators.validate_image_extension])),
                ('season_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='player.host')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayListEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_e', to='player.episode')),
                ('playlist_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_na', to='player.playlist')),
            ],
            options={
                'verbose_name': 'PlayListTrack',
                'verbose_name_plural': 'PlayListTracks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favouritelist', to='player.episode')),
            ],
            options={
                'verbose_name': 'FavouriteList',
                'verbose_name_plural': 'FavouriteLists',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='host_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode_h', to='player.host'),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode_c', to='player.podcastcategory'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode_s', to='player.season'),
        ),
    ]
