# Generated by Django 4.0.6 on 2022-07-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='MusicAlbum',
        ),
        migrations.RenameModel(
            old_name='Artist',
            new_name='MusicArtist',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='MusicGenre',
        ),
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='MusicLyrics',
        ),
        migrations.RenameModel(
            old_name='PlayListTracks',
            new_name='MusicPlayListTracks',
        ),
        migrations.RenameModel(
            old_name='Track',
            new_name='MusicTrack',
        ),
    ]
