# Generated by Django 4.0.6 on 2022-07-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(default='Unknown PlayList', max_length=100)),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='playlist', to='player.track')),
            ],
            options={
                'verbose_name': 'PlayList',
                'verbose_name_plural': 'PlayLists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='favouritelist', to='player.track')),
            ],
            options={
                'verbose_name': 'FavouriteList',
                'verbose_name_plural': 'FavouriteLists',
                'ordering': ['id'],
            },
        ),
    ]
