# Generated by Django 4.0.6 on 2022-07-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_playlisttracks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttracks',
            name='playlist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='playlist_na', to='player.playlist'),
        ),
    ]
