# Generated by Django 4.0.6 on 2022-07-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_rename_favouritelist_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_description',
        ),
    ]
