# Generated by Django 4.0.6 on 2022-07-22 07:05

import company_profile.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(default='Kin Ideas', max_length=100)),
                ('contact_person', models.CharField(default='Pawlos Girma', max_length=100)),
                ('address', models.CharField(default='22, Around Awraris Hotel, Teshab Building, 5th Floor', max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('state', models.CharField(default='Addis Ababa', max_length=100)),
                ('postal_code', models.CharField(default='-', max_length=100)),
                ('email', models.EmailField(default='admin@kinideas.com', max_length=100)),
                ('office_Phone_number', models.CharField(default='+251 XXX XXX XXX', max_length=100)),
                ('mobile_Phone_number', models.CharField(default='+251 9XX XXX XXX', max_length=100)),
                ('fax', models.CharField(default='+251 XXX XXX XXX', max_length=100)),
                ('website', models.URLField(default='www.kinideas.com', max_length=100)),
                ('banner', models.ImageField(max_length=1023, upload_to=company_profile.models.banner_images, validators=[core.validators.validate_image_extension])),
                ('logo', models.ImageField(max_length=1023, upload_to=company_profile.models.logo_images, validators=[core.validators.validate_image_extension])),
                ('privecy', models.TextField(max_length=1023)),
                ('terms', models.TextField(max_length=1023)),
                ('help', models.TextField(max_length=1023)),
                ('about', models.TextField(max_length=1023)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfiles',
                'ordering': ['id'],
            },
        ),
    ]
