# Generated by Django 4.0.6 on 2022-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='lyrics_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
