# Generated by Django 4.0.6 on 2022-07-28 12:27

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, default='Unknown Station', max_length=100, unique=True)),
                ('station_frequency', models.FloatField(default=88)),
                ('station_url', models.CharField(default='', max_length=1023)),
                ('station_cover', models.ImageField(blank=True, unique=True, upload_to=player.models.Station_Cover_Images, validators=[core.validators.validate_image_extension])),
                ('station_description', models.TextField(blank=True, max_length=1023, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favouritelist', to='player.station')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
                'ordering': ['id'],
            },
        ),
    ]
